on: push
name: Build and deploy GH Pages
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          lfs: 'true'
      - name: build_and_deploy
        uses: shalzz/zola-deploy-action@master
        env:
          # Target branch to store compiled pages on
          PAGES_BRANCH: gh-pages
          OUT_DIR: .build
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
